version: '2'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
      - CONFIG_LOAD_SAMPLE=false
      - db=redis
      - workflow_dynomite_cluster_hosts=redis:6379:us-est-1c
      - workflow_elasticsearch_url=es:9300
      - conductor_additional_modules=com.netflix.conductor.contribs.NatsStreamModule
      - loadSample=false
      - io_nats_streaming_url=nats://ubuntu:4222
      - io_nats_streaming_clusterId=faas-cluster
      - io_nats_streaming_clientId=conductor
      - io_nats_streaming_qGroup=qGroup
      - io_nats_streaming_durableName=durable
    image: niemen/conductor-server-es6:2.4
    networks:
      - internal
    ports:
      - 8080:8080
    links:
      - elasticsearch:es
      - redis:redis

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: niemen/conductor-ui:2.0.0
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    networks:
      - internal
    ports:
      - 6379:6379

  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300

networks:
  internal:
